N_DISTANCE_SENSORS = [-90, -60, -30, 0, 30, 60, 90]

CAMERA_HEIGHT = 20

CAMERA_WIDTH = 20

CAMERA_DEPT = 1

SENSOR_SHAPE = (len(N_DISTANCE_SENSORS)+1, )
CAMERA_SHAPE = (CAMERA_HEIGHT, CAMERA_WIDTH, CAMERA_DEPT, )
